### ISSUE TITLE
Qwik formAction with zod preprocess isnt possible

### ISSUE THREAD

**Issue by DustinJSilk** [fabian-hiller/modular-forms#109]
Hi, firstly thanks for such an amazing library! I'm sure a ton of work has gone into it.

Im struggling to apply a zod preprocess function using Qwik without running into various type errors.

Essentially, I have a field that is type `string[]` and I'm trying to render it into a single input as a comma separated string.
Previously, I had it working with a preprocess function that split and validated the strings as individual emails. I cant seem to get it working after adding modular forms to my project as the schema cant be used in the zodForm$ function.

Here is some example code that will show various type errors.

```tsx
import { component$, useTask$ } from '@builder.io/qwik';
import { routeLoader$, z } from '@builder.io/qwik-city';
import { formAction$, reset, useForm, zodForm$ } from '@modular-forms/qwik';

export const useNotification = routeLoader$(() => {
  return {
    billings: ['user@example.com']
  }
})

const zodEmail = z.preprocess(
  (val: unknown) => String(val).split(/,\s*/).filter((s) => !!s),
  z.array(z.string().email()),
)

const schema = z
  .object({
    billings: zodEmail,
  })
  .strict()

type NotificationsForm = z.infer<typeof schema>

export const useFormAction = formAction$<NotificationsForm>(async (data, ev) => {
  // do something
}, zodForm$(schema))

export default component$(() => {
  const notifications = useNotification()

  const [form, { Form, Field }] = useForm<NotificationsForm>({
    loader: notifications,
    action: useFormAction(),
    validate: zodForm$(() => schema),
    validateOn: 'submit',
  })

  useTask$(({ track }) => {
    track(() => notifications.value)
    reset(form, { initialValues: notifications.value })
  })

  return <Form>
    <Field name="carbonReports">
      {(field, props) => <input {...props} value={field.value}/>}
    </Field>
  </Form>
})
```

I would really appreciate any help. Either in the form of a fix or some advice to solving this another way.
THanks again!

**Comment by fabian-hiller** [comment]
If I understand you correctly, you want to convert a comma separated string of emails into an array. This would mean that the input of a field has a different type than the output. Currently this behavior is not supported by Modular Forms. Modular Forms currently uses the schema only for validation. I think the errors will go away if you use `z.input` instead of `z.infer`.

You can now do the following: If you need the array in your component, I suggest to do the conversion with (or without) your schema in `useComputed$` independently from Modular Forms. If you need the array in your action, I recommend to do the conversion directly in the action yourself.

Furthermore, if you are interested in saving bundle size, you can validate your form with my new project Valibot: https://github.com/fabian-hiller/valibot

**Comment by fabian-hiller** [comment]
Yes Zod currently requires at least 11 KB, even for simple schemas. Valibot is supported in the latest version of Modular Forms in conjunction with Qwik. Native support in Qwik independent of Modular Forms will probably follow next week.

https://modularforms.dev/qwik/guides/validate-your-fields#schema-validation

**Comment by DustinJSilk** [comment]
Amazing! I’ll scope it out soon, thanks!

**Comment by fabian-hiller** [comment]
You can check the bundle size with bundlejs.

Zod: https://bundlejs.com/?q=zod&treeshake=%5B%7B+string+%7D%5D
Valibot: https://bundlejs.com/?q=valibot&treeshake=%5B%7B+string+%7D%5D
