### ISSUE TITLE
[Suggestion] Remove "of" property from Field

### ISSUE THREAD

**Issue by Sharlaan** [fabian-hiller/modular-forms#12]
Hello i just discovered SolidJS and this ReactHookForm-like version, very nice !

But i noticed in docs the Field is duplicating `of={logingForm}` while it is already defined in parent component `<Form of={logingForm}`.  
Also a Field will most probably never be used outside of a Form ?

Suggestion: maybe there is a way for Field to grab of's value from Form ?

Edge case: if used inside a native form element, Field could make the "of" property as required only in the case where not used as child of Form ?

**Comment by fabian-hiller** [comment]
Technically it is possible, e.g. with the context API, to remove the `of` property from the fields. However, this would have the disadvantage that the type safety is lost and also the auto-completion in the editor no longer works, since this information comes from the return value of `createForm`.

As the name says, it is a modular library, which means that only the code you use ends up in your bundle. This reduces the bundle size to a minimum and provides better performance since the browser has to process less JavaScript. Of course, this has not only advantages. One tradeoff of this is that we have to pass the return value of `createForm` to all other calls, since it contains the state and type information. I think it is worth it and in my eyes it improves the readability of the code.

**Comment by fabian-hiller** [comment]
@Sharlaan do you have feedback or more questions for me? Or should I close the issue?
