### ISSUE TITLE
Qwik - Form resets on validation error.

### ISSUE THREAD

**Issue by jmcelreavey** [fabian-hiller/modular-forms#33]
This could be a Qwik issue rather than a Modular-Forms issue but I'd like to get thoughts on it.

I have the following page:

```typescript
import { component$, useStylesScoped$, useSignal } from "@builder.io/qwik";
import { routeLoader$, z } from "@builder.io/qwik-city";
import {
  formAction$,
  useForm,
  zodForm$,
  type InitialValues,
} from "@modular-forms/qwik";
import ContactStyles from "./contact.css?inline";

const contactSchema = z.object({
  name: z.string().min(5),
  message: z.string().min(5),
});

type ContactForm = z.input<typeof contactSchema>;

export const useFormLoader = routeLoader$<InitialValues<ContactForm>>(() => ({
  name: "",
  message: "",
}));

export const useFormAction = formAction$<ContactForm>((values) => {
  return {
    errors: { name: "Name is already taken" },
    // Form response
    response: {
      status: "error",
      message: "An error has occurred.",
    },
  };
}, zodForm$(contactSchema));

export default component$(() => {
  useStylesScoped$(ContactStyles);
  const formVisible = useSignal(false);
  const [, { Form, Field }] = useForm<ContactForm>({
    loader: useFormLoader(),
    action: useFormAction(),
    validate: zodForm$(contactSchema),
  });

  return (
    <article>
      <h2>Contact</h2>
      <button onClick$={() => (formVisible.value = true)}>Contact Me</button>

      {formVisible.value && (
        <Form>
          <Field name="name">
            {(field, props) => (
              <>
                <label for={field.name}>Your name</label>
                <input {...props} type="text" />
                {field.error && <div>{field.error}</div>}
              </>
            )}
          </Field>
          <Field name="message">
            {(field, props) => (
              <>
                <label for={field.name}>Your name</label>
                <textarea {...props} />
                {field.error && <div>{field.error}</div>}
              </>
            )}
          </Field>
          <button>Send</button>
        </Form>
      )}
    </article>
  );
});
```

When I submit the page for the first time it resets the form even though no redirect has occurred and there's validation errors. After the first submit it keeps the input values as expected.

Demo:

https://user-images.githubusercontent.com/6317960/227277985-6e1c3305-6eb3-4e1a-ae9a-6f7a0785613f.mp4

**Comment by fabian-hiller** [comment]
The problem is that Qwik re-renders your fields and does not keep the previous HTML elements, so the value of the `<input />` element is lost. This may even be a bug on the part of Qwik (or Modular Forms), since HTML elements should only be recreated if really necessary.

You now have two simple ways to prevent this. First, you can make your fields controlled. This way the state of your form is the source of truth and changes to the state will automatically update the UI. You can read more about this here: https://modularforms.dev/guides/controlled-fields

On the other hand, you can prevent rendering by changing `{field.error && <div>{field.error}</div>}` to `<div>{field.error}</div>`. This way the template can't change and Qwik can make the DOM updates fine-grained.

**Comment by jmcelreavey** [comment]
Great documentation once again, was able to fix it easily by making the fields controlled.
