### ISSUE TITLE
[Qwik] Support Date in FieldValues

### ISSUE THREAD

**Issue by GrandSchtroumpf** [fabian-hiller/modular-forms#34]
Hello, 
I'm trying to select a date in my form but I've got some issues. I've tried with and without `NoSerialize` (note: Qwik does serialize Date)

### Without NoSerialize
```typescript
type TimestampForm = {
  date: NoSerialize<Date>;
}

// ERROR: Type 'Date' is not assignable to type 'FieldValues'
export const useTimestampAction = formAction$<TimestampForm>((values) => {
  console.log(values);
});
```

### With NoSerialize
```typescript
type TimestampForm = {
  date: NoSerialize<Date>;
}

// ERROR: Type 'Date & { __no_serialize__: true; }' is not assignable to type 'FieldValues'
export const useTimestampAction = formAction$<TimestampForm>((values) => {
  console.log(values);
});
```

**Comment by fabian-hiller** [comment]
`Date` is currently not a supported data type, as there is no HTML form element that natively supports it. Instead, we work with strings, which can be converted to a `Date` object afterwards. What exactly do you have in mind?

**Comment by GrandSchtroumpf** [comment]
An `input` element as 3 types that return a Date : 
- `type="date"`
- `type="datetime-local"`
- `type="time"`

Example:
```html
<form onSubmit="submit">
   <!-- You can replace type with datetime-local or time -->
  <input id="date" type="date" />
</form>
<script>
  function submit(event) {
    event.preventDefault();
    console.log(document.getElementById('date').valueAsDate);
  }
</script>
```

**Comment by fabian-hiller** [comment]
Thank you for bringing `valueAsDate` to my attention. Possibly you are right and my previous statement was wrong. I will check this and see if an integration makes sense.

**Comment by fabian-hiller** [comment]
I have now read up a bit. `valueAsDate` and `valueAsNumber` are IDL attributes (also known as a JavaScript propertyies). This means that `valueAsDate` and `valueAsNumber` cannot be passed as HTML attributes to the element. So setting the current date is only possible via JavaScript using the DOM API. https://developer.mozilla.org/en-US/docs/Glossary/IDL

Qwik could theoretically add this as a feature as I understand it. Until that happens, I am unsure if we should support `Date` as it is cumbersome to convert a `Date` to a matching string to make fields controlled. More on controlled fields here: https://modularforms.dev/guides/controlled-fields

Controlled fields are important because they consider the state of the form that Modular Forms manages internally as the source of truth, and changes to the state automatically update the UI. This is required for much of Modular Forms' feature set.

**Comment by fabian-hiller** [comment]
I am closing the issue but am open to reopen it if there are good arguments to include `Date`. What advantages would it have for you or what is the reason that you want to use the `Date` object instead of a string? This info might help me make a good decision in the long run.

**Comment by GrandSchtroumpf** [comment]
Isn't Controlled field something that is managed by the developer ?
Maybe I'm wrong, but to me a developer should be able to create custom component that manage the IO of the fields: 
```jsx
    <Field name="date">
        {(field, props) => {
        return <input 
          type="datetime-local"
          onInput$={$((_: Event, element: HTMLInputElement) => {
            const field = getFieldStore(form, name);
            updateFieldValue(form, field, name, element.valueAsDate);
          })}
        />
      })}
    </Field>
```

For me, the question is more: is it serializable by qwik so it can enter inside the `SubmitHandler` & `formAction$`.
So far what I understand is that `Date`:
- will be serialized/deserialized by `$` so it should work inside `SubmitHandler`
- but it's not serialized/deserialized by `globalAction$` so it won't work with `formAction$`

------
I would like to keep `Date` around in the `SubmitHandler` to manage cross-field manipulation / validation based on `Date` manipulation. Also, as a typescript experience being able to specify that a field is a Date and not a string really improve devX and maintainability in the codebase.

**Comment by fabian-hiller** [comment]
Basically you can manage IO of the fields manually with the help of the provided methods, e.g. `setValue`, `setError` and `validate`. However, Modular Forms also tries to reduce the developer's effort in a sensible way, which is why we capture the input by default, but leave the output to the developer to be as compatible as possible with custom components and external UI libraries.

Theoretically, `globalAction$` can transfer only strings and files via the `<form />` element without JavaScript. However, Modular Forms allows to handle arrays, booleans and numbers by additional information from the developer. Accordingly, we could also support the `Date` object here. More about this here: https://modularforms.dev/guides/enhanced-forms

I think this discussion is good and I am curious to hear more opinions. Currently I still tend to leave it up to the developer to convert the string to a date, for example to do calculations. Optionally, we could also provide a `getElements` method to access `valueAsDate` to avoid having to do the conversion ourselves.

For date string validation you can use `required`, `pattern`, `maxRange`, `minRange` or `custom`.

**Comment by fabian-hiller** [comment]
I could imagine adding an `asDate` or `dataType="date"` property to the `Field` component to tell Modular Forms to capture the value as a date instead of a string. I could implement this without a breaking change in the next few days. Feel free to make thoughts on the API design and share them with me.

**Comment by fabian-hiller** [comment]
Do you prefer `asDate` or `dataType="date"`?

**Comment by GrandSchtroumpf** [comment]
I guess `dataType="xxx"` would be more future proof

**Comment by fabian-hiller** [comment]
Your issue gave me an idea. Modular Forms is almost completely type safe. The only and maybe even most important place that is not type safe is connecting the `Field` component to an HTML element. So far, the data type that is ultimately captured is dependent on the HTML element, since we have no information at runtime about the data type defined via TypeScript. Meaning, if you define the data type `boolean` but add `<input type="number" />`, a number will be captured instead of a boolean.

However, if we add a property to the `Field` component that contains the type information, we can use it to capture the correct value with the correct data type. Thus, for `<input type="date" />` you can decide between `string`, `number` and `Date`. Depending on your selection we capture the value via `value`, `valueAsNumber` or `valueAsDate`. On the one hand, this gives you the freedom of choice over the data type and allows you to use the full functionality of an HTML element and, on the other hand, you can be sure that only the correct data type is captured.

For the data type `string` I would make the specification of the property optional. For all other data types, it is mandatory. Since we can make the property type-safe, the editor will alert you in case of an error and can complete the value via autocompletion for you, just like with the `name` property.

```tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from '@builder.io/qwik-city';
import { type InitialValues, useForm } from '@modular-forms/qwik';

type RegisterForm = {
  name: string;
  age: number;
  dateOfBirth: Date;
  hobbies: string[];
};

export const useFormLoader = routeLoader$<InitialValues<RegisterForm>>(() => ({
  name: '',
  age: undefined,
  dateOfBirth: undefined,
  hobbies: [],
}));

export default component$(() => {
  const [registerForm, { Form, Field }] = useForm<RegisterForm>({
    loader: useFormLoader(),
  });

  return (
    <Form>
      <Field name="name">
        {(field, props) => <input {...props} type="text" />}
      </Field>
      <Field name="age" type="number">
        {(field, props) => <input {...props} type="number" />}
      </Field>
      <Field name="dateOfBirth" type="Date">
        {(field, props) => <input {...props} type="date" />}
      </Field>
      <Field name="hobbies" type="string[]">
        {(field, props) => (
          <select {...props} multiple>
            <option value="music">Music</option>
            <option value="sports">Sports</option>
            <option value="other">Other</option>
          </select>
        )}
      </Field>
      <input type="submit" />
    </Form>
  );
});
```

What do you think about it? I appreciate feedback to better decide if I should implement this.

**Comment by GrandSchtroumpf** [comment]
Hmmm let's say I want to store a list of movies (all fields being serializable by qwik) for example instead of a list of string. How would that work ?
I feel like limiting the available fields to a list of primitive might be restrictive. In my app I always need to select a object with a drop-down and do something with it.
I personally wouldn't limit the amount of types that are possible to store. As long as it's serializable it should be ok. But I understand if it's not what you want to do with this library.

**Comment by fabian-hiller** [comment]
It is possible to keep complex objects and arrays in the store of Modular Forms. In our playground we have a simple example of this with the todo form. However, since Modular Forms focuses on handling and validating native HTML form fields, the value of a field must be of type `FieldValue`. Otherwise, submitting the form to your server without JavaScript will not work either. For storing other values Modular Forms is not necessary. For this you can use directly the `useSignal` or `useStore` hook of Qwik. Following are some helpful links.

https://modularforms.dev/playground/todos
https://modularforms.dev/guides/enhanced-forms
https://modularforms.dev/guides/nested-fields
https://modularforms.dev/guides/field-arrays

**Comment by GrandSchtroumpf** [comment]
Ok, thx I didn't understand that modular forms with qwik was for native HTML controllers. 
Then I guess using `type` in field is fine as we know exactly the amount of types managed by native html tags !

**Comment by fabian-hiller** [comment]
Native date objects are supported now.

**Comment by iamriajul** [comment]
@fabian-hiller Failed to use `Date` with valibot's `date()`, client-side validation passes normally but server-side validation fails with the error message passed to `date()`.
After inspection I've seen the ModularForms submitting date data like this: `2023-10-26T00:00:00.000Z` 
but when I use `document.querySelector('input[name=date]')` to inspect it results: `2023-10-26`
but when I use `getValue(form, 'date')` it results: `2023-10-26T00:00:00.000Z`.

I'm using transformer described as ModularForms.dev like this:
```tsx
  // Transform date or number to string
  const input = useComputed$(() => {
    const value = field.value;
    if (!value) {
      return undefined;
    }
    if (!Number.isNaN(typeof field.value as unknown == "number" ? field.value : (field.value as Date).getTime())) {
      return new Date(field.value).toISOString().split("T", 1)[0];
    }
    return undefined;
  });

//jsx
<input
        value={input.value}
        {...props}
      />
```

**Comment by fabian-hiller** [comment]
Have you read [this](https://modularforms.dev/qwik/guides/enhanced-forms) guide? I need more code to help you.
