### ISSUE TITLE
Redirect not working in formAction$

### ISSUE THREAD

**Issue by juanpmarin** [fabian-hiller/modular-forms#48]
Hi! Thanks for your amazing work, this lib fills many gaps

I'm trying to do a redirect after processing some values, like this:
```
export const useFormAction = formAction$((values, { redirect }) => {
  console.log("VALUES", values);

  throw redirect(301, "/reports");
}, zodForm$(businessInfoSchema));
```
 But it just does not work

**Comment by fabian-hiller** [comment]
I @juanpmarin, thank you very much! There was a similar [issue](https://github.com/fabian-hiller/modular-forms/issues/31) about this before, best read up there and then report here if the problem persists. Since `formAction$` builds on `globalAction$` from Qwik, the problem, if it exists, is probably on Qwik's side. In this case, you should create an issue at Qwik.

**Comment by juanpmarin** [comment]
Hi @fabian-hiller, thanks for your answer 
I had the same form implemented with `globalAction$` and the redirect did work.
Like this:

```
const InfoBusinessSchema = {
  companyName: z.string().min(3),
  monthDeliveries: z.string(),
  phone: z.string().min(10),
};

export const usePostInfoBusiness = globalAction$(
  ({ companyName, monthDeliveries, phone }, { redirect }) => {
    console.log({ companyName, monthDeliveries, phone });

    throw redirect(301, "/reports");
  },
  zod$(InfoBusinessSchema)
);
```

**Comment by fabian-hiller** [comment]
Interesting. I will investigate this later. Maybe it is related to the update of Qwik in v0.6.0. Otherwise, I am at a loss as `formAction$` builds on `globalAction$` and we have not added any code that affects redirects.

**Comment by juanpmarin** [comment]
@fabian-hiller I'm sorry, it appears to be a bug in my code!!
Thanks again for your help
