### ISSUE TITLE
formAction$ uses globalAction$

### ISSUE THREAD

**Issue by tuurbo** [fabian-hiller/modular-forms#63]
Qwik offers routeAction$ and globalAction$. Is there possibly a security concern with formAction$ only using globalAction$? https://qwik.builder.io/docs/action/#route-vs-global-actions 

This is just a suggestion, but maybe routeAction$ should be the default for formAction$? But with something like globalFormAction$ offered if needed? Or keep it the same and offer routeFormAction$?

Sorry to nitpick. Great work with Modular Forms so far!

**Comment by fabian-hiller** [comment]
You are right, `formAction$` builds on `globalActionQrl`. `globalActionQrl` in turn builds on `routeActionQrl` and the additional code seems to do almost "nothing": https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/server-functions.ts#L153-L165

I can't imagine that using `globalActionQrl` instead of `routeActionQrl` poses a security problem. Nevertheless, I will check with Manu how I should proceed here.

**Comment by fabian-hiller** [comment]
The difference seems to be that a `routeAction$` can only be accessed within the file in the `routes` directory, whereas with `globalAction$` the action is made globally accessible via the context.

It is also unclear to me so far with the actions whether a person can access other people's data by guessing the action ID. I will inform myself about this.

**Comment by fabian-hiller** [comment]
According to Miško's information and the official documentation it is not possible to use `routeAction$` outside the `routes` directory or a `plugin@...` file. So it is not possible to use `routeAction$` for the implementation of Modular Forms. According to Miško's answers and my own assessment `globalAction$` is not a security problem. I therefore close this issue.
