### ISSUE TITLE
Conditionally rendering on submitting results in empty values and no validation

### ISSUE THREAD

**Issue by marcusbuffett** [fabian-hiller/modular-forms#67]
https://stackblitz.com/edit/modular-forms-solid-gluqpu?file=src/routes/login.tsx

When you press submit, check the console: values is an empty object, no email. If you extract the form outside of the Show, or change the `when` to something else, it's fine

**Comment by fabian-hiller** [comment]
This behavior is expected. Modular Forms detects if a field is in the DOM and sets a `active` state depending on it. If a field is inactive its value is not captured by default. You can see this behavior [here](https://modularforms.dev/solid/playground/payment) in the debugger when you change the value of the `type` field. This behavior allows optional fields to be captured only when necessary.

In your example the following happens. After the form is submitted, the state of `submitting` is set to `true`. Then the values of the fields are retrieved and passed to your `onSubmit` handler. However, since setting `submitting` causes the `Show` component to remove the fields from the DOM, they are marked as inactive and no longer end up in the final values of the form. The source code of the `Form` component can be found [here](https://github.com/fabian-hiller/modular-forms/blob/main/packages/solid/src/components/Form.tsx).

For a quick fix, you can either tell the [`Form`](https://modularforms.dev/solid/api/Form) component with the `shouldActive` property to also capture the values of inactive fields, or you can individually tell each [`Field`](https://modularforms.dev/solid/api/Field) component with the `keepActive` property to keep it active. If more people approach me with this "problem", I will think about whether it would be useful to revise the implementation. For example, I could try capturing the values before setting the `submitting` state to `true`.

**Comment by marcusbuffett** [comment]
Gotcha, yeah I get how it’s expected from the implementation details, but definitely comes across as a bug, and a hard one to debug at that. I also don’t think it’s too rare of a pattern to hide the form and show a loader instead while it’s submitting, so I’m guessing other people will run into this.

It’s easy to work-around once you know what the issue is, but sort of mysterious and unexpected imo.

**Comment by fabian-hiller** [comment]
You are right that this is somewhat unexpected and probably most would expect different behavior. I'll give it some thought. However, do not expect a quick reaction. I do not have so much time at the moment.

**Comment by armandsalle** [comment]
Hey, I'm getting this issue too, with fields that are in popover components. I try to add `shouldActive` `keepActive` etc but it doesn't work...

https://github.com/fabian-hiller/modular-forms/assets/28579123/77a426c5-c72d-4ec5-90f1-533ab51bceea

So to make it works I added hidden inputs in the page
```ts
<FieldArray name="tags" keepActive>
    {(fieldArray) => (
      <For each={fieldArray.items}>
        {(_, index) => (
          <Field name={`tags.${index()}`}>
            {(_, props) => (
              <input {...props} type="text" class="sr-only" />
            )}
          </Field>
        )}
      </For>
    )}
</FieldArray>
```

The result

https://github.com/fabian-hiller/modular-forms/assets/28579123/2b99151a-fd01-45ed-a7c6-aa7819d970e4

I hope it will help other people facing this "issue"

**Comment by fabian-hiller** [comment]
Hey @armandsalle I think the problem has a different origin with you. Can you provide me a minimal reproduction in StackBlitz? You can fork [my project](https://stackblitz.com/edit/modular-forms-solid) and use it as a template.

**Comment by fabian-hiller** [comment]
I have thought about this issue again. On one hand, I understand the problem and agree that this is somewhat unexpected. On the other hand, I think it is a bad practice to remove the elements with `Show` from the DOM for accessibility reasons. Instead, the relevant information should be passed to the user in some other way. For example, by using the `disabled` attribute in combination with CSS for visual feedback. For this reason, I don't want to make any changes to the code of the library for the time being. Nevertheless, should other people encounter similar problems, I will think about it again.
