### ISSUE TITLE
Yup validator support

### ISSUE THREAD

**Issue by sbesh91** [fabian-hiller/modular-forms#84]
Adding [yup validation](https://github.com/jquense/yup) would be a big win for me and my team as we're considering a port of our forms from Formik.  Would a yup adapter be possible here just as we have the zod adapter?

**Comment by fabian-hiller** [comment]
Yes that is possible. Either submit a PR similar to the [Zod adapter](https://github.com/fabian-hiller/modular-forms/blob/main/packages/react/src/adapters/zodForm.ts) or I tried to create a suitable adapter tomorrow.

**Comment by sbesh91** [comment]
If you'd be up for taking a first pass at the adapter, I would appreciate that.  If it becomes a nightmare for you and isn't worth the time, I can give it a shot since it would unlock a migration path for my team.

**Comment by fabian-hiller** [comment]
Are you using React with Preact Signals? Otherwise I'm not sure if Modular Forms works for you.

**Comment by sbesh91** [comment]
Yes we are on React with Preact Signals.

**Comment by fabian-hiller** [comment]
I'm sorry I can't get around to it today. Can you submit a PR or send me a code example here so that the effort on my side is less?

If there is no error, an empty object must be returned. If there are errors, an object with all errors must be returned. The keys of the object correspond to the field names and the values of the error messages. Attached is a pseudocode example:

```ts
if (errors) {
  return {
    fieldName: 'Error message',
    'nested.fieldName': 'Error message',
    'array.3.fieldName': 'Error message',
  }
}

return {}
```

Here is the code of the adpaters: https://github.com/fabian-hiller/modular-forms/tree/main/packages/react/src/adapters

**Comment by sbesh91** [comment]
I've taken a multi-variant approach today.  
1.  I wanted to run this experiment with zod to see if my team would be interested
2.  I will next take a look at writing the yup adapter

I got some really good reviews on the experiment with zod, so that may mean we don't rely on yup in the long run.  I'd still like to take a look at the yup adapter, but don't worry about making it your priority now that my team has taken to liking zod.

**Comment by fabian-hiller** [comment]
Since there is currently no need, I am closing this issue. If this changes in the future, I can open it again.
