### ISSUE TITLE
required validation is skipped

### ISSUE THREAD

**Issue by kkharji** [fabian-hiller/modular-forms#9]
Hello,

I'm trying to have a reactive value of two form fields, which I managed to do with the following: 

```javascript
createMemo(() => {
    const firstName = useField(form, "firstName").value;
    const lastName = useField(form, "lastName").value;
    return `${firstName} ${lastName}`
  })
```

However, when I submit `fistName` cand `lastNamed` required validation get skipped.

Not sure, maybe required isn't checking for empty string 🪵 or useField influences validation and creating a bug.

commenting out `useField` fixes the issue and required validation works

Regards

**Comment by fabian-hiller** [comment]
Hey, you should not use the primitive [`useField`](https://modularforms.dev/api/useField) for this. Use the [`getValue`](https://modularforms.dev/api/getValue) method instead. If there is still a bug, please provide me more of your code.

**Comment by fabian-hiller** [comment]
The `useField` primitive is used internally in the `Field` component to set up a field and provide its reactive properties and state. By presumably using the `Field` component in your JSX code and also using the `useField` primitive in `createMemo`, you override the `validate` property.

I have improved the API documentation so that it is now a bit clearer what the `useField` primitive does and that to access the value of a field, as in this case, the `getValue` method should be used. Thank you for highlighting this issue!

**Comment by kkharji** [comment]
Amazing thanks @fabian-hiller 🙏
